name: Build and publish deployment images
on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-tests-success:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tests-passed: ${{ steps.set-output.outputs.tests-passed }}
    steps:
      - name: Check tests workflow result
        id: set-output
        run: |
          echo "tests-passed=true" >> "$GITHUB_OUTPUT"

  build-php-8-2:
    needs: check-tests-success
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      php_version: '8.2'
    secrets: inherit

  build-php-8-3:
    needs: check-tests-success
    uses: ./.github/workflows/docker-publish-image.yml
    with:
      php_version: '8.3'
    secrets: inherit
